CREATE DATABASE employee;
use employee;

CREATE TABLE proj_table(
PROJECT_ID CHAR(10) PRIMARY KEY,
PROJ_NAME	VARCHAR(100),
DOMAIN	    VARCHAR(100),
START_DATE	 DATE,
CLOSURE_DATE DATE,
DEV_QTR	    CHAR(10),
STATUS      VARCHAR(50)
);

CREATE TABLE emp_record_table(
EMP_ID	   CHAR(10) PRIMARY KEY,
FIRST_NAME	VARCHAR(100),
LAST_NAME	VARCHAR(100),
GENDER	    CHAR(5),
ROLE	    VARCHAR(100),
DEPT	    VARCHAR(100),
EXP	        INT,
COUNTRY	    VARCHAR(100),
CONTINENT	VARCHAR(100),
SALARY	    INT,
EMP_RATING	INT,
MANAGER_ID	CHAR(10),
PROJ_ID     CHAR(10),
FOREIGN KEY (PROJ_ID) REFERENCES Proj_table(PROJECT_ID)
);

CREATE TABLE data_science_team(
EMP_ID	    CHAR(10) PRIMARY KEY,
FIRST_NAME  VARCHAR(100),
LAST_NAME	VARCHAR(100),
GENDER	    CHAR(5),
ROLE	    VARCHAR(100),
DEPT	    VARCHAR(100),
EXP	         INT,
COUNTRY	    VARCHAR(100),
CONTINENT   VARCHAR(100),
FOREIGN KEY (EMP_ID) REFERENCES emp_record_table(EMP_ID)
);

ALTER TABLE emp_record_table
ADD CONSTRAINT fk_manager
FOREIGN KEY (MANAGER_ID) REFERENCES emp_record_table(EMP_ID);












